-- employee - id ,name
-- department - id & name 
-- employee_department - eid , did 
-- salary - salary
-- select e.name,d.name 
-- from 
-- employee e join employee_department ed on ed.eid = e.id 
-- join 
-- department d on d.id = ed.did ;

-- select salary from salary_table order by salary desc 